learning:

  vae:
    num_epochs: 25
    learning_rate: 0.001
    schd_gamma: 0.99

  latent_mapper:
    num_epochs: 15
    learning_rate: 0.01
    schd_gamma: 0.9

  classifier:
    num_epochs: 80
    learning_rate: 0.001
    schd_gamma: 0.99

  net:
    num_epochs: 30
    learning_rate: 0.001
    schd_gamma: 0.9

  batch_size: 256
  device: 'cuda:0'
  pseudo_labelling_confidence_threshold: 0.9

loss:
  reconstruction_term_weight: 1
  kl_term_weight: 1
  vae_term_weight: 1
  classification_term_weight: 10
  contrastive_term_weight: 0.1
  contrastive_temperature: 0.5

data:
  in_channels: 3
  num_classes: 10
  num_labeled: 1000
  image_dim: 32

model:
  vae_hidden_dim: 1024
  vae_latent_dim: 64
  cls_latent_dim: 16
  lm_hidden_dims: [32] 

paths:
  weights_root: ./weights
  report_root: ./reports
  rec_results: ./reconstruction_samples


# pretrained: ~
# ckpt_save_freq: 10
# n_samples_per_class: 100
# train_data_path: ./data/CIFAR10/train/
# test_data_path: ./data/CIFAR10/train/
# load_saved_model: False
# ckpt_load_path: False